name: CI/CD - Dev Environment

on:
  push:
    branches:
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - dev

jobs:
  validate-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Validate commit messages (Conventional Commits)
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            style
            refactor
            test
            perf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate latest commit message (Conventional Commits)
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit message: '$COMMIT_MSG'"
          echo "$COMMIT_MSG" | grep -Eq '^(feat|fix|chore|docs|style|refactor|test|perf)(\(.+\))?: .+' || {
            echo "❌ Commit message does not follow Conventional Commits."
            exit 1
          }

  build-and-push:
    runs-on: ubuntu-latest
    needs: [validate-pr, validate-push]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CICD_USERNAME }}
          password: ${{ secrets.CICD_PASSWORD }}

      - name: Build and push backend1 (dev)
        uses: docker/build-push-action@v5
        with:
          context: ./backend1
          push: true
          tags: ${{ secrets.CICD_USERNAME }}/backend1:dev-${{ github.sha }}

      - name: Build and push backend2 (dev)
        uses: docker/build-push-action@v5
        with:
          context: ./backend2
          push: true
          tags: ${{ secrets.CICD_USERNAME }}/backend2:dev-${{ github.sha }}

      - name: Build and push frontend (dev)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.CICD_USERNAME }}/frontend:dev-${{ github.sha }}
